= TP 1

== Avant tout

- Créez un nouveau Repl sur https://repl.it
- nommez le "TP - cours 01"
- Les exercices suivants devront être écrit dans ce Repl.
- Ecrivez le code de vos exercices, en gardant bien ce que vous avez déjà écrit pour les exercices précédents.


== Exercice 1 : Concaténation

Stockez dans des variables les valeurs suivantes : 

- Votre nom : X
- Votre age : Y
- Votre activité préféré : Z

Puis complètez avec ces données la phrase suivante : 

"X, personne de Y ans est recherchée pour activité illégale de Z. Récompense : 50 000€"

Vous afficherez la phrase obtenue dans la console.

Note : Parce que vous êtes des gens biens, vous n'utiliserez pas X,Y et Z comme variables. 
A la place, vous utiliserez des noms de variables plus à propos.
Ce commentaire est valable pour les autres exercices.


== Exercice 2 : Calcul de fou !

Stockez dans des variables les valeurs suivantes :

- Votre année de naissance
- Une année future (Genre 2021) : X

Puis vous afficherez dans la console la phrase suivante :

"En X j'aurais entre Y et Z ans"

Avec X et Y les deux ages possibles pour l'année. 
Exemple : "En 2019, j'aurais entre 35 et 36 ans"

== Exercice 3 : Un petit tour et puis s'en vont

Ici, on va faire un petit peu de mathématique : en calculant la circonférence d'un cercle.

La formule mathématique est : `2r x π` avec R le rayon du cercle.

En JS, π est défini via cette valeur : `Math.PI`

- Commencez par afficher dans la console la valeur de π
- Puis créez une fonction qui prend en paramètre le rayon et qui retourne la circonférence.
- En utilisant cette fonction, affichez dans la console la circonférence d'un cercle de rayon 256.


== Exercice 4 : Et dieu créa la femme

Créez une fonction "createPerson" avec comme paramètres 

- name : le nom de la personne
- alimentPrefere : son aliment préféré

Cette fonction doit retourner un objet avec : 

- un attribut "name"
- une methode "aime" qui a un paramètre "aliments" et qui retourne vrai si cet aliments équivaut à alimentPrefere
- une methode "mange" avec un paramètre "aliments" et qui retourne une chaine de caractères : name + " mange des " + aliments

Sous votre code, ajoutez celui-ci :

[source,javascript]
----
    
 var valentine = createPerson("Valentine","carottes");

 console.log(valentine.name); // affiche Valentine
 console.log(valentine.aime("carottes")); // affiche true
 console.log(valentine.mange("carottes")); // affiche Valentine mange des carottes

----

Les console.log() doivent afficher les valeurs misent respectivement en commentaire

== Exercice 5 : En condition

- Ecrivez une fonction qui renvoient la valeur la plus grande entre deux valeurs.
- A l'aide de cette fonction, affichez dans la console, la valeur la plus grande entre 42 et 418.

== Exercice 6 : Un chat ou deux chats?

- Ecrivez une fonction `plurialize` avec deux paramètres :
  - un nom commun : X
  - le nombre de X : Y

Cette fonction retourne le nom au pluriel (en ajoutant un `s`) si Y est supérieur à 1

- En utilisant `plurialize`, affichez dans la console la phrase : "Chez moi, j'ai Y X" avec Y valant 0, 1 et 2.