= TP 4
:source-highlighter: highlightjs

== Avant tout

- Créez un nouveau Repl **HTML, CSS, JS** sur https://repl.it
- nommez le "TP4"
- Les exercices suivants devront être écrit dans ce Repl.
- Ecrivez le code de vos exercices, en gardant bien ce que vous avez déjà écrit pour les exercices précédents.

Pour l'ensemble des exercices, vous utiliserez le code HTML suivant. A copier/coller dans le fichier **index.html** de votre **repl**

[source,HTML]
----
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>TP4</title>
    <link href="index.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <article class="main-article">
      <header>
        <h1 class="article-title">Le top 5 des titres putaclic</h1>
      </header>
      <ul class="top5">
        <li>L’histoire de ce Patrick vous redonnera foi en l’humanité</li>
        <li>10 raisons pour lesquelles les Bretons sont ouf!</li>
        <li>Comment faire un high-kick en 5 étapes faciles</li>
        <li>10 choses qu’on ne vous dit pas sur les caribous</li>
        <li>Les 10 chats les plus stupides du monde</li>
      </ul>
      <ul class="top10">
      </ul>
    </article>
    <footer>
        <div>
            <button type="button" class="js-toggle-colors-button">Changer les couleurs</button>
        </div>
        <div>
            <button type="button" class="js-add-title-button">Ajouter un titre</button>
            <input type="text" name="title" class="js-add-title-input" placeholder="Nouveau titre" value="">
        </div>
        <div>Nombre de titres : <span class="js-titles-count"></span></div>
    </footer>
    <script src="index.js"></script>
  </body>
</html>
----

Ainsi que le code CSS suivant (à mettre dans index.css):

[source,CSS]
----

    .red-color {
        color: red;
    }

----

Pour l'ensemble des exercices, ce code ne devrait jamais être modifier à la main.

== Exercice 1

Afficher dans la console le text du titre de l'article de classe "article-title".

Attention, celà doit afficher "Le top 5 des titres putaclic" et non "<h1 class="article-title">Le top 5 des titres putaclic</h1>" ou "HTMLHeadingElement {}"


== Exercice 2
Afficher dans la console le texte de chacun des élements *li* de l'élement *ul* de classe *top5*

L'affichage doit se faire de la façon suivant : 

<numéro de liste> : <titre>

Et pour être plus exacte, vous devez avoir cette affichage en console : 

----
      1 : L’histoire de ce Patrick vous redonnera foi en l’humanité
      2 : 10 raisons pour lesquelles les Bretons sont ouf!
      3 : Comment faire un high-kick en 5 étapes faciles
      4 : 10 choses qu’on ne vous dit pas sur les caribous
      5 : Les 10 chats les plus stupides du monde
----

== Exercice 3

Soit le tableau 

[source,javascript]
----
var titles = [
    'Faut-il interdire les frites ?',
    'Les 10 tendances 2018 de la chipolata',
    'Les 10 types de chats',
    '10 questions à vous poser avant de vous cogner contre un mur',
    '10 secrets pour marcher droit'
]
----

Ecrivez un code qui prend chaque élement de la liste **titles** pour l'afficher sous forme d'element de liste HTML (**li**) 
dans la liste HTML de classe **top10** déjà présent dans le code HTML fournit initialement.

Vous devez obtenir l'affichage suivant : 

[source,HTML]
----
<ul class="top10">
    <li>Faut-il interdire les frites ?<li>
    <li>Les 10 tendances 2018 de la chipolata<li>
    <li>Les 10 types de chats<li>
    <li>10 questions à vous poser avant de vous cogner contre un mur<li>
    <li>10 secrets pour marcher droit<li>
</ul>
----

Une fois fait, en utilisant Javascript, changer le titre de l'article par **"Le top 10 des titres putaclic"**

== Exercice 4

Vous aller écrire un code qui lors d'un click sur le bouton "Changer les couleurs" va changer la couleur de l'article 
en rouge. Si on re-clique d-sur le bouton, la couleur revient au noir.

Pour celà, il faut :

- Récupérer l'evenement **"click"** sur le bouton de classe **js-toggle-colors-button**.
- Récupérer l'element  de classe **main-article**
- Utiliser la propriété **className**
- Utiliser le style '.red-color' définit dans le fichier **index.css**
- Faire en sorte qu'au click de souris, on alterne entre le rouge et le noir.

== Exercice 5

Ajouter des titres

Dans le code HTML, vous noterez la présence de cette section : 

[source,HTML]
----
    <div>
        <button type="button" class="js-add-title-button">Ajouter un titre</button>
        <input type="text" name="title" class="js-add-title-input" placeholder="Nouveau titre" value="">
    </div>
----

C'est un bouton et un champ de saisi. 
Le but de l'exercice est de faire que quand :

- On saisi du texte dans le champ de saisi
- Puis on clique sur le bouton

Celà ajoute le texte saisi à la suite de la liste de classe .top10.

Pour information, pour récupéré la valeur d'un champ de saisi, celà se fait comme ceci : 

[source,javascript]
----

    var input = document.querySelector(".monChamp");
    var value = input.value;
    // C'est l'attribut 'value' qui est permet de récuperer la valeur saisie.
----

== Exercice 6

Vous partirez de votre base de code de l'exercice 5.
Quand un titre est ajouter, vous devez recupérer le nombre de titres putaclics dans la page et l'afficher en bas de page
dans l'espace ci-dessous.

[source,HTML]
----
 <div>Nombre de titres : <span class="js-titles-count"></span></div>
----

[NOTE]
----
Les titres putaclics sont tous contenu dans des **li**. Et tout les **li** de la page contiennent forcement des titres putaclics.
----

Bonus : afficher le nombre de titres putaclics au chargement de la page.